name: Hello

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          chmod +x ./install_criterion.sh
          ./install_criterion.sh
          ./build.sh
      - name: unit_tests
        run: |
          ./build/bin/test
